# Generated by Django 3.2 on 2021-06-27 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(default='Orlando', max_length=30, verbose_name='Nome')),
                ('last_name', models.CharField(default='Godinho Belchior', max_length=30, verbose_name='Sobrenome')),
                ('age', models.IntegerField(verbose_name='Idade')),
                ('birth_date', models.DateField(null=True, verbose_name='Data de Nascimento')),
                ('email', models.EmailField(max_length=254, null=True, verbose_name='Email')),
                ('surname', models.CharField(max_length=30, null=True, verbose_name='Apelido')),
                ('observation', models.TextField(null=True, verbose_name='Observação')),
            ],
            options={
                'ordering': ['first_name', 'last_name'],
            },
        ),
    ]
