# Generated by Django 3.2 on 2021-06-28 01:17

from django.db import migrations, models
import statics.randomName


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='person',
            options={'ordering': ['first_name']},
        ),
        migrations.AlterField(
            model_name='person',
            name='first_name',
            field=models.CharField(default=statics.randomName.RandomName, max_length=30, verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='person',
            name='last_name',
            field=models.CharField(max_length=30, verbose_name='Sobrenome'),
        ),
        migrations.AlterField(
            model_name='person',
            name='observation',
            field=models.TextField(blank=True, null=True, verbose_name='Observação'),
        ),
        migrations.AlterField(
            model_name='person',
            name='surname',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Apelido'),
        ),
    ]
