# Generated by Django 3.2 on 2021-06-28 01:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0003_alter_person_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='person',
            options={'ordering': ['first_name', 'last_name']},
        ),
    ]
