# Generated by Django 3.2 on 2021-06-28 01:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0004_alter_person_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='person',
            options={},
        ),
    ]
